apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset
spec:
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://192.168.49.2:8443
          - cluster: engineering-prod
            url: https://192.168.49.2:8443
  template:
    metadata:
      name: "{{cluster}}-hello-world"
    spec:
      project: default
      source:
        repoURL: https://github.com/pratclot/argo-test.git
        targetRevision: main
        path: hello-world/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: hello-world
