name: Bump Docker Container Version

env:
  IMAGE_NAME: hello-world

permissions:
    contents: write 

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    # Shold really be a custom image that has necessary build tools.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        # from https://github.com/actions/checkout/issues/13#issue-481453396
      - name: Setup git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@github.com"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Bump version
        run: |
          # Your version bumping logic here
          # For example, you can use a tool like bump2version or manually update the version in a file
          # This example uses bump2version for a Python project
          pip install bump2version
          bump2version patch

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          export VERSION=$(grep -Po 'current_version = \K[^ ]+' .bumpversion.cfg)
          # exports the version across the whole pipeline
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          docker buildx build --push -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:"${VERSION}" .

      - name: Push git tag
        run: |
          git push origin
          git push origin --tags
